<?php
/** @var ProductAssemblyService $block */

use BIWAC\AssemblyService\Block\ProductAssemblyService;
use Magento\Framework\Exception\NoSuchEntityException;

try {
    $assemblyProduct = $block->getProduct();
} catch (NoSuchEntityException $e) {
    echo $e->getMessage();
}
?>

<?php if (isset($assemblyProduct) && $block->getConfig()->isEnabled() && $block->hasParentAssemblyService()): ?>
    <div id="product-recommendation-detailpage-related-placeholder" class="closed">
        <form data-role="tocart-form" action="<?php try {
            echo $block->getAddToCartUrl();
        } catch (NoSuchEntityException $e) {
            echo $e->getMessage();
        } ?>" method="post">
            <h3><?php echo $assemblyProduct->getName(); ?></h3>
            <div class="price-box price-final_price"
                 data-role="priceBox"
                 data-product-id="<?php echo $assemblyProduct->getId() ?>"
                 data-price-box="product-id-<?php echo $assemblyProduct->getId() ?>">
                <span class="price"><?php echo $assemblyProduct->getPrice(); ?></span>
            </div>
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="btn">
                <button type="submit" title="Add to Cart" class="action tocart primary">
                    <span>Add to Cart</span>
                </button>
            </div>
        </form>
    </div>
<?php endif; ?>
